BookApp.Web/Controllers/MyBookController.cs
using BookApp.Services.Data.Interfaces;
using BookApp.Web.ViewModels.Book;
using BookApp.Web.ViewModels.MyBook;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookApp.Web.Controllers
{
    [Authorize]
    public class MyBookController : Controller
    {
        private readonly IMyBookService myBookService;
        public MyBookController(IMyBookService myBookService)
        {
            this.myBookService = myBookService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<IndexMyBookViewModel> books =
                await this.myBookService.IndexGetAllAsync();

            return View(books);
        }
    }
}

BookApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - BookApp.Web</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/BookApp.Web.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookApp.Web</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">All Books</a>
						</li>
						@if (User?.Identity?.IsAuthenticated ?? false)
						{
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="MyBook" asp-action="Index">My Books</a>
								</li>

							@if (User.IsInRole("Admin"))
							{
										<li class="nav-item">
											<a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Panel</a>
										</li>
							}
						}
					</ul>
					<form asp-controller="Book" asp-action="Index" method="get" class="d-flex">
						<input type="text" name="searchString" class="form-control me-2" 
						placeholder="Search books..." value="@ViewData["SearchString"]" />
						<button type="submit" class="btn btn-outline-success">Search</button>
					</form>
					<ul class="navbar-nav ms-auto">
						@if (User?.Identity?.IsAuthenticated ?? false)
						{
								<li class="nav-item">
									<a class="nav-link text-dark" id="logout" href="/Identity/Account/Logout">Logout</a>
								</li>
						}
						else
						{
								<li class="nav-item">
									<a class="nav-link text-dark" id="register" href="/Identity/Account/Register">Register</a>
								</li>
								<li class="nav-item">
									<a class="nav-link text-dark" id="login" href="/Identity/Account/Login">Login</a>
								</li>
						}
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2024 - BookApp.Web
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>